### ISSUE TITLE
Notifications pop too much/often

### ISSUE THREAD

**Issue by neemzy** [janisz/StashNotifier#1]
Hi!

The plugin works great, but by default (with a pull interval of 10 secondes), closed notifications reappear almost instantly, which is quite disturbing. Using a wider pull interval (I chose the maximum value, 890 seconds) fixes this, but on the other hand I obviously lose much of the plugin's interest regarding reactivity.

Would there be any way to memorize which PRs have been notified to the user to put them in a "blacklist" and make them not show up again? Ideally, they should be removed from the list when the user approves it so it pops again in case of automatic unapproval.

Regards,

**Comment by janisz** [comment]
Actually it's done that way. There is [`openedNotifications`](https://github.com/janisz/StashNotifier/blob/master/background.js#L66) array which contains [clicked](https://github.com/janisz/StashNotifier/blob/master/background.js#L10-L13) notifications ids. If `openedNotifications` contains this id ([code](https://github.com/janisz/StashNotifier/blob/master/background.js#L3)), notification should not appear again. 
Nevertheless I'll take a look at that issue. Thanks for reporting.

**Comment by janisz** [comment]
@neemzy I can confirm, that bug exists. When you click to open notification it won't appear again (until plugin reload, browser restart etc) But when you click on small `x` to just close it, it will reappear. I think it will be easy to fix. Stay tuned.

**Comment by neemzy** [comment]
Ah right, I guess I didn't try clicking the notifications directly. Thanks for the update, looking forward to hear from you :)

**Comment by janisz** [comment]
The fix is ready. You can use it by cloning branch and loading it from disk (could require developer mode). I hope I'll find time to make release next week. 
Again, thanks for reporting.
